name: "Startup Grind BCN"
description: "Website for the Startup Grind Barcelona."
url: "http://www.startupgrind.cat"
markdown: redcarpet
pygments: true
permalink: /blog/:year/:month/:day/:title
exclude: [
  'Gemfile', 'Gemfile.lock', 'startup-grind-bcn.sublime-project',
  'startup-grind-bcn.sublime-workspace', 'config', 'bundle', 'Rakefile'
]
assets:
  js_compressor: uglifier
  css_compressor: yui