name: "Startup Grind BCN"
title: "Startup Grind Barcelona"
description: "Website for Startup Grind Barcelona."
url: "https://www.startupgrind.cat"
markdown: redcarpet
pygments: true
permalink: /blog/:year/:month/:day/:title
exclude: [
  'Gemfile', 'Gemfile.lock', 'startup-grind-bcn.sublime-project',
  'startup-grind-bcn.sublime-workspace', 'config', 'bundle', 'Rakefile'
]
environment: development
assets:
  js_compressor: uglifier
  css_compressor: yui
